In [1]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [4]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[1, 0, 0, 1],
        [2, 8, 6, 6],
        [1, 0, 8, 7]])

In [7]:
torch.rand(3, 4)

tensor([[0.6802, 0.5746, 0.0774, 0.0490],
        [0.2739, 0.3700, 0.8214, 0.1752],
        [0.0507, 0.6003, 0.6294, 0.8248]])

In [8]:
torch.randn((3,4))

tensor([[-1.7149, -0.7261, -1.2183,  0.7695],
        [-0.7582, -0.9010,  0.9488,  0.7523],
        [ 1.0816,  0.8895, -0.9933, -0.6069]])

In [9]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
